### ISSUE TITLE
Your name in list of Racket 7.3 release contributors?

### ISSUE THREAD

**Issue by jbclements** [yjqww6/drcomplete#15]
Okay, this isn't really an issue; I'm working on the release announcement for Racket 7.3, and I'm wondering how you'd like your name to appear. Here's the list as I have it now:

The following people contributed to this release: Alex Harsányi,
Alexander McLin, Alexander Shopov, Alexis King, Alex Knauth, Andrew
Kent, Bert De Ketelaere, Ben Greenman, Fred Fu, Georges Dupéron, Greg
Hendershott, Gustavo Massaccesi, Jay McCarthy, Jesse Alama John
Clements, Jordan Johnson, Kimball Germane, Lassi Kortela, Leif Andersen
Leo Uino, Marc Kaufmann, Matthew Butterick, Matthew Flatt, Matthias
Felleisen Michael MacLeod, Mike Sperber, Paulo Matos, Philip McGrath
Philippe Meunier, Pierre-Evariste Dagand, qww6, Robby Findler, Ron
Garcia, Ryan Culpepper, Ryan Kramer Sam Tobin-Hochstadt, Shu-Hung You,
Sorawee Porncharoenwase, Spencer Florence Spencer Mitchell, Stephen De
Gabrielle, Vincent St-Amour, Vladilen Kozin, Winston Weinert, yjqww6,
Wayo Cavazos

You can reach me at 

clements@racket-lang.org

Please feel free to close this "issue". 

Thanks!

John Clements

**Comment by jbclements** [comment]
Also... is the "qww6" entry also you?

Thanks again!

John Clements

**Comment by yjqww6** [comment]
Yes, qww6 is me. Looks like I have inconsistent git configs on multiple machines, sorry.
I would like my github id, yjqww6, to be used, thanks.

**Comment by jbclements** [comment]
Okay, got it. Thanks!

John Clements
