### ISSUE TITLE
Autocomplete in interactions window

### ISSUE THREAD

**Issue by a11ce** [yjqww6/drcomplete#16]
drcomplete-auto doesn't function in the interactions window, would this be possible to add? I'm not sure if drcomplete itself does as I can't figure out how to manually trigger it.

**Comment by yjqww6** [comment]
`C-/` should trigger autocomplete. 
`drcomplete-auto` should work in interaction window, could you elaborate?

But for candidates, it does compute the list only from definition window. So if you define things only in interaction window, there would not appear in candidates. This could be fixed via `namespace-mapped-symbols`, probably.

**Comment by a11ce** [comment]
It does work now, I'm not sure why it wasn't when I tried. Sorry!
