### ISSUE TITLE
[feature request] automatic autocomplete

### ISSUE THREAD

**Issue by florence** [yjqww6/drcomplete#6]
As things stand I need to explicitly activate autocomplete with CMD-/.

Since this package makes autocomplete good enough to be useful, it would be nice if autocomplete automatically activated like in other editors (when not in comments, text, or strings probably).

**Comment by yjqww6** [comment]
Thanks for your feedback!
Actually @Syntacticlosure has implemented such a plugin(see https://github.com/Syntacticlosure/smart-completion), but I also remember the author told me it didn't work smoothly enough currently.
I didn't have a try and will do some experiment in a few days.

**Comment by yjqww6** [comment]
@Syntacticlosure contribute his code as `drcomplete-auto` here, and after a few adjustments it seems fine now.

**Comment by florence** [comment]
Thanks to you both! :)
